GET http://localhost:8080/jsf-web-app/api/v1/todo/all

###

GET http://localhost:8080/jsf-web-app/api/v1/todo/6

###

POST http://localhost:8080/jsf-web-app/api/v1/todo
Content-Type: application/json

{
  "categoryId": 2,
  "categoryName": "Trash",
  "description": "Namaniac",
  "targetDate": "2020-12-12"
}

###

PUT http://localhost:8080/jsf-web-app/api/v1/todo
Content-Type: application/json

{
  "categoryId": 2,
  "categoryName": "Trash",
  "description": "Namaniac",
  "id": 12,
  "targetDate": "5555-12-12"
}

###

DELETE http://localhost:8080/jsf-web-app/api/v1/todo/11